### PR TITLE
Update Live.ts

### PR DESCRIPTION
**Pull request by c86ec23b-fef1-4979-b2fa-b9adc351b8cc**
### Why:

Closes [issue link]

### Confirm the following:
- [x] I have tested these changes (by compiling, running, and playing) and have seen no unintended differences in gameplay

### CODE REVIEW

**Comment by Nul-led** [comment]
Maybe rename to isHostile, but i kinda dislike the idea of having an extra field on living entities for that tbh, it should be part of the ai object instead :v

**Comment by ABCxFF** [comment]
What does this fix @c86ec23b-fef1-4979-b2fa-b9adc351b8cc ?

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
@ABCxFF a lot

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
@Nul-led if its only on the ai file then struff like tankbody cant have it

**Comment by Nul-led** [comment]
> @ABCxFF a lot

Can you elaborate?

**Comment by Nul-led** [comment]
> @Nul-led if its only on the ai file then struff like tankbody cant have it

Thats the point lol

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
@Nul-led but its supposed to

**Comment by ABCxFF** [comment]
Yeah please elaborate, or lmk on discord

**Comment by Nul-led** [comment]
Day 60 of asking wtf dis for

**Comment by Nul-led** [comment]
lol

**Pull request closed without merging**
