### PR TITLE
Add windows installer and run .bat

### PR DESCRIPTION
**Pull request by n0deee**
### Why:
This will make it easier for users to install and run the server, making it only necessary to run installer-windows.bat and run-windows.bat

### Confirm the following:
- [x] I have tested these changes (by compiling, running, and playing) and have seen no unintended differences in gameplay

### CODE REVIEW

**Comment by n0deee** [comment]
It can still be improved but that's already a stopgap

**Comment by ABCxFF** [comment]
@xScripty @Nul-led you run windows right? Would one of you mind testing this, I run on Mac OS

**Comment by Nul-led** [comment]
Dont have my laptop until next week so no :v

**Comment by ABCxFF** [comment]
@c86ec23b-fef1-4979-b2fa-b9adc351b8cc

**Comment by supahero1** [comment]
Broken @n0deee 
image

**Comment by supahero1** [comment]
works on win10

**Comment by ABCxFF** [comment]
Thank you.

**Comment by Nul-led** [comment]
Closing due to discussion on discord server.

**Pull request closed without merging**
